# Generated by Django 3.2.7 on 2022-03-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(null=True)),
                ('character', models.IntegerField(blank=True, null=True)),
                ('consonant', models.IntegerField(blank=True, null=True)),
                ('vowel', models.IntegerField(blank=True, null=True)),
                ('average_lens', models.FloatField(blank=True, null=True)),
                ('longest_word', models.CharField(blank=True, max_length=100, null=True)),
                ('repeated_char', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
