# Generated by Django 3.2.7 on 2022-03-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(null=True)),
                ('character', models.IntegerField()),
                ('consonant', models.IntegerField()),
                ('vowel', models.IntegerField()),
                ('average_lens', models.FloatField()),
                ('longest_word', models.CharField(max_length=100)),
                ('repeated_char', models.TextField()),
            ],
        ),
    ]
