# Generated by Django 3.2.7 on 2022-03-02 09:35

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('character', models.IntegerField()),
                ('consonant', models.IntegerField()),
                ('vowel', models.IntegerField()),
                ('average_lens', models.SmallIntegerField()),
                ('longest_word', models.CharField(max_length=100)),
                ('repeated_char', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
