# Generated by Django 3.2.7 on 2022-03-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quote', '0002_rename_quotes_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='average_lens',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='character',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='consonant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='longest_word',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='repeated_char',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='vowel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
