# Generated by Django 3.2.7 on 2022-03-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quote', '0004_alter_quote_average_lens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.TextField(null=True),
        ),
    ]
